### ISSUE TITLE
Reduce compression in era5 monthly average datasets

### ISSUE THREAD

**Issue by imreddyTeja** [CliMA/ClimaArtifacts#85]
As Kevin and Kat discovered, opening highly compressed NetCDF files is slow. Regenerate era5 monthly average artifacts at lower deflate_level

- [x] (Optional) Create profiling script to compare deflate levels
- [x] Reduce deflate level in era5_monthly_averages_2008
- [x] Reduce deflate level in era5_monthly_averages_pressure_levels_1979_2024
- [x] Reduce deflate level in era5_monthly_averages_single_level_1979_2024

**Comment by Sbozzolo** [comment]
Note that if the files are not used for the evolution, it might not matter as much
